# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/foodfriend/img')),
                ('age', models.IntegerField(null=True)),
                ('sex', models.IntegerField(choices=[(0, 'Choose your gender:'), (1, 'Woman'), (2, 'Man')], default=0)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('factor', models.FloatField(choices=[(0, 'Choose your Activity Factor:'), (1.0, '1.0 - no exercise, desk job'), (1.2, '1.2 - little exercise, desk job'), (1.4, '1.4 - light exercise or sports 1-3 days/wk'), (1.6, '1.6 - moderate exercise or sports 3-5 days/wk'), (1.8, '1.8 - hard exercise or sports 6-7 days/wk'), (2.0, '2.0 - hard daily exercise or sports & physical labor job or 2 X day training, football camp, etc')], default=0)),
                ('target', models.IntegerField(choices=[(0, 'Choose your target:'), (1, 'Build muscle'), (2, 'Loose fat')], default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
