# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('kcal', models.FloatField()),
                ('proteins', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('grams', models.FloatField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.IntegerField(choices=[(0, 'Choose meal type:'), (1, 'Breakfast'), (2, 'Breakfast II'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Supper')], default=0)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodfriend.Days')),
                ('foods', models.ManyToManyField(blank=True, to='foodfriend.Food')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/foodfriend/img')),
                ('age', models.IntegerField(null=True)),
                ('sex', models.IntegerField(choices=[(0, 'Choose your gender:'), (1, 'Woman'), (2, 'Man')], default=0)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('factor', models.FloatField(choices=[(0, 'Choose your Activity Factor:'), (1.0, '1.0 - no exercise, desk job'), (1.2, '1.2 - little exercise, desk job'), (1.4, '1.4 - light exercise or sports 1-3 days/wk'), (1.6, '1.6 - moderate exercise or sports 3-5 days/wk'), (1.8, '1.8 - hard exercise or sports 6-7 days/wk'), (2.0, '2.0 - hard daily exercise or sports & physical labor job or 2 X day training, football camp, etc')], default=0)),
                ('target', models.IntegerField(choices=[(0, 'Choose your target:'), (1, 'Build muscle'), (2, 'Loose fat')], default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='days',
            name='date_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodfriend.UserExtend'),
        ),
        migrations.AlterUniqueTogether(
            name='days',
            unique_together=set([('date', 'date_user')]),
        ),
    ]
