# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('date_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodfriend.UserExtend')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('kcal', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=64)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodfriend.Days')),
                ('foods', models.ManyToManyField(to='foodfriend.Food')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodfriend.UserExtend')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='meal_food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodfriend.Meal'),
        ),
    ]
