# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Breakfast II'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Supper')], default=1),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
    ]
