# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0002_auto_20170118_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='grams',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='meal_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodfriend.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodfriend.Days'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foodfriend.UserExtend'),
        ),
    ]
