# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0003_auto_20170118_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='meal_food',
        ),
        migrations.AlterUniqueTogether(
            name='days',
            unique_together=set([('date', 'date_user')]),
        ),
    ]
