# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 19:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0004_auto_20170219_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='grams',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.FloatField(blank=True, default=100, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
