# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0004_auto_20170118_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.IntegerField(choices=[(0, 'Choose meal type:'), (1, 'Breakfast'), (2, 'Breakfast II'), (3, 'Lunch'), (4, 'Dinner'), (5, 'Supper')], default=0),
        ),
    ]
