# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0005_auto_20170118_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='person',
        ),
    ]
