# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0006_remove_meal_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(blank=True, null=True, to='foodfriend.Food'),
        ),
    ]
