# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfriend', '0007_auto_20170119_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(blank=True, to='foodfriend.Food'),
        ),
    ]
